In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [2]:
import pandas as pd

In [3]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
np.random.seed(1)
import sklearn
import sklearn.model_selection
import sklearn.metrics
import sklearn.ensemble
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
from matplotlib import rc
%matplotlib inline

In [4]:
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import f1_score
from sklearn.metrics import auc
from sklearn.metrics import precision_score, recall_score
import pickle
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import LeaveOneOut 
from sklearn.model_selection import cross_val_score

In [8]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [6]:
models = []
models.append(('LogR', LogisticRegression()))
models.append(('gNB', GaussianNB()))
models.append(('SVM', SVC(kernel = 'rbf', probability=True)))
models.append(('DT', DecisionTreeClassifier(criterion = 'entropy', random_state=1)))
models.append(('RF', RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state=0)))
models.append(('KNN', KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('mNB', MultinomialNB()))
models.append(('ABC', AdaBoostClassifier()))
models.append(('GBC', GradientBoostingClassifier()))
models.append(('ETC', ExtraTreesClassifier()))
models.append(('BC', BaggingClassifier()))

In [7]:
dataset = ['https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_doripenem_PA.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_clindamycin_CJ.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_doripenem_EcS.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_doripenem_KN.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_ertapenem_EcS.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_ertapenem_KN.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_imipenem_EcS.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_imipenem_KN.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_kanamycin_SE.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_meropenem_EcS.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_meropenem_KN.csv',
          'https://raw.githubusercontent.com/safaet/antimicrobial_resistance/main/Data/Read%20Data/amr_ast_streptomycin_SE.csv']

In [9]:
len(dataset)

12

In [28]:
df = pd.read_csv(dataset[4])

In [29]:
df.head()

,Isolate,aac(3)-II=COMPLETE,aac(3)-II=HMM,aac(3)-IIa=COMPLETE,aac(3)-IIa=PARTIAL_END_OF_CONTIG,aac(3)-IId=COMPLETE,aac(3)-IV=COMPLETE,aac(3)-Ib=COMPLETE,aac(3)-VIa=COMPLETE,aac(6')-IIc=COMPLETE,...,sul3=PARTIAL_END_OF_CONTIG,tet(A)=COMPLETE,tet(A)=PARTIAL,tet(A)=PARTIAL_END_OF_CONTIG,tet(B)=COMPLETE,tet(D)=COMPLETE,tet(M)=COMPLETE,tet(X)=COMPLETE,uhpT_E350Q=POINT,ertapenem
0,PDT000201874.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,PDT000102024.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,PDT000149559.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,PDT000543117.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,PDT000140740.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
file_out = 'result_csv_file/amr_ast_streptomycin_SE_result.csv'

In [30]:
# slice dataset and store in df2
df2 = df.iloc[:, 1:-1]

In [12]:
df2.head()

,aac(3)-I=COMPLETE,aac(3)-IIIa=COMPLETE,aac(3)-Ic=COMPLETE,aac(3)=HMM,aac(6')-29b=COMPLETE,aac(6')-33=COMPLETE,aac(6')-IIc=COMPLETE,aac(6')-Ib'=COMPLETE,aac(6')-Ib-cr5=COMPLETE,aac(6')-Ib3=COMPLETE,...,msr(E)=COMPLETE,qnrA1=COMPLETE,rmtD=COMPLETE,sul1=COMPLETE,sul1=PARTIAL,sul1=PARTIAL_END_OF_CONTIG,tet(A)=COMPLETE,tet(A)=PARTIAL,tet(C)=COMPLETE,tet(G)=COMPLETE
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [31]:
df['sum'] = df2.sum(axis=1)

In [32]:
df.head()

,Isolate,aac(3)-II=COMPLETE,aac(3)-II=HMM,aac(3)-IIa=COMPLETE,aac(3)-IIa=PARTIAL_END_OF_CONTIG,aac(3)-IId=COMPLETE,aac(3)-IV=COMPLETE,aac(3)-Ib=COMPLETE,aac(3)-VIa=COMPLETE,aac(6')-IIc=COMPLETE,...,tet(A)=COMPLETE,tet(A)=PARTIAL,tet(A)=PARTIAL_END_OF_CONTIG,tet(B)=COMPLETE,tet(D)=COMPLETE,tet(M)=COMPLETE,tet(X)=COMPLETE,uhpT_E350Q=POINT,ertapenem,sum
0,PDT000201874.2,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,5
1,PDT000102024.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5
2,PDT000149559.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5
3,PDT000543117.1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,7
4,PDT000140740.2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7

In [33]:
y = df.pop('ertapenem')

In [34]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
scaler = MinMaxScaler()

In [36]:
scaled_column = scaler.fit_transform(df['sum'].values.reshape(-1, 1))

In [37]:
df['sum'] = scaled_column

In [20]:
df.shape

(44, 166)

In [293]:
# import matplotlib.pyplot as plt

In [38]:
X = df.iloc[:,1:]
# y = df.iloc[:, -1]

In [44]:
# X.pop("aac(6')-29b=COMPLETE")

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Algorithm Implement

In [40]:
mode = []
tr_precision=[]
tr_recall = []
tr_f1 = []
tr_accu = []

te_precision=[]
te_recall = []
te_f1 = []
te_accu = []

In [24]:
for name, model in models:
    model = model.fit(X_train, y_train)
    mode.append(name)
    
    Y_train_pred = model.predict(X_train)
    Tr_precision = precision_score(y_train, Y_train_pred, average='macro').round(3)
    tr_precision.append(Tr_precision)
    
    Tr_recall = recall_score(y_train, Y_train_pred, average='macro').round(3)
    tr_recall.append(Tr_recall)
    
    Tr_f1 = f1_score (y_train, Y_train_pred, average='macro').round(3)
    tr_f1.append(Tr_f1)
    
    accuracy = model.score(X_train, y_train).round(3)
    tr_accu.append(accuracy)

    # dict = {'classifier': name, f'tr_precision{i+1}': Tr_precision, f'tr_recall{i+1}': Tr_recall, f'tr_f1 {i+1}':Tr_f1}

    # df = pd.DataFrame(dict)

    # print('Model_Name: ', model)
    # print('Tr_precision: ', Tr_precision)
    # print('Tr_recall: ', Tr_recall)
    # print('Tr_f1: ', Tr_f1)    
    # print("--------------")

    # i+=1

In [25]:
for name, model in models:
    model = model.fit(X_train, y_train)
    # mode.append(model)
    
    Y_test_pred = model.predict(X_test)
    report = sklearn.metrics.classification_report(y_test, Y_test_pred)
    Te_precision = precision_score(y_test, Y_test_pred, average='macro').round(3)
    te_precision.append(Te_precision)
    
    Te_recall = recall_score(y_test, Y_test_pred, average='macro').round(3)
    te_recall.append(Te_recall)
    
    Te_f1 = f1_score (y_test, Y_test_pred, average='macro').round(3)
    te_f1.append(Te_f1)
    
    accuracy = model.score(X_test, y_test).round(3)
    te_accu.append(accuracy)

    # print('Model_Name: ', model)
    # print("Report: ", report)
    # print('Te_precision: ', Te_precision)
    # print('Te_recall: ', Te_recall)
    # print('Te_f1: ', Te_f1)
    # print("--------------")

In [42]:
# Implement ANN Model


# Define the Model
ANN = Sequential([Dense(64, activation='relu', input_shape=(X_train.shape[1],)), Dropout(0.5),
                   Dense(32, activation='relu'),
                   Dropout(0.5), Dense(1, activation='sigmoid')])

# Compile the model
ANN.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = ANN.fit(X_train, y_train, epochs=25, batch_size=32, validation_split=0.2)

# Evaluate the model

loss, accuracy = ANN.evaluate(X_test, y_test)

Epoch 1/25
3/3 [==============================] - 4s 374ms/step - loss: 0.7251 - accuracy: 0.4878 - val_loss: 0.6461 - val_accuracy: 0.6190
Epoch 2/25
3/3 [==============================] - 0s 54ms/step - loss: 0.7150 - accuracy: 0.5122 - val_loss: 0.6377 - val_accuracy: 0.7143
Epoch 3/25
3/3 [==============================] - 0s 68ms/step - loss: 0.7047 - accuracy: 0.4878 - val_loss: 0.6306 - val_accuracy: 0.7619
Epoch 4/25
3/3 [==============================] - 0s 64ms/step - loss: 0.6519 - accuracy: 0.6098 - val_loss: 0.6216 - val_accuracy: 0.8095
Epoch 5/25
3/3 [==============================] - 0s 59ms/step - loss: 0.6744 - accuracy: 0.6098 - val_loss: 0.6105 - val_accuracy: 0.7619
Epoch 6/25
3/3 [==============================] - 0s 57ms/step - loss: 0.6354 - accuracy: 0.6220 - val_loss: 0.5980 - val_accuracy: 0.8095
Epoch 7/25
3/3 [==============================] - 0s 52ms/step - loss: 0.5941 - accuracy: 0.7195 - val_loss: 0.5837 - val_accuracy: 0.8095
Epoch 8/25
3/3 [==============================] - 0s 63ms/step - loss: 0.5973 - accuracy: 0.7439 - val_loss: 0.5683 - val_accuracy: 0.8095
Epoch 9/25
3/3 [==============================] - 0s 54ms/step - loss: 0.6136 - accuracy: 0.6829 - val_loss: 0.5538 - val_accuracy: 0.9048
Epoch 10/25
3/3 [==============================] - 0s 72ms/step - loss: 0.6011 - accuracy: 0.6463 - val_loss: 0.5414 - val_accuracy: 0.9048
Epoch 11/25
3/3 [==============================] - 0s 58ms/step - loss: 0.5906 - accuracy: 0.7805 - val_loss: 0.5302 - val_accuracy: 0.9048
Epoch 12/25
3/3 [==============================] - 0s 64ms/step - loss: 0.5698 - accuracy: 0.7561 - val_loss: 0.5182 - val_accuracy: 0.9048
Epoch 13/25
3/3 [==============================] - 0s 55ms/step - loss: 0.5625 - accuracy: 0.7317 - val_loss: 0.5058 - val_accuracy: 0.9048
Epoch 14/25
3/3 [==============================] - 0s 56ms/step - loss: 0.5448 - accuracy: 0.7561 - val_loss: 0.4919 - val_accuracy: 0.9048
Epoch 15/25
3/3 [==============================] - 0s 54ms/step - loss: 0.5523 - accuracy: 0.7195 - val_loss: 0.4763 - val_accuracy: 0.9048
Epoch 16/25
3/3 [==============================] - 0s 69ms/step - loss: 0.5212 - accuracy: 0.7683 - val_loss: 0.4618 - val_accuracy: 0.9048
Epoch 17/25
3/3 [==============================] - 0s 59ms/step - loss: 0.4854 - accuracy: 0.8293 - val_loss: 0.4481 - val_accuracy: 0.9048
Epoch 18/25
3/3 [==============================] - 0s 50ms/step - loss: 0.5034 - accuracy: 0.7927 - val_loss: 0.4359 - val_accuracy: 0.9048
Epoch 19/25
3/3 [==============================] - 0s 63ms/step - loss: 0.4668 - accuracy: 0.8293 - val_loss: 0.4260 - val_accuracy: 0.9048
Epoch 20/25
3/3 [==============================] - 0s 49ms/step - loss: 0.4372 - accuracy: 0.8659 - val_loss: 0.4162 - val_accuracy: 0.9048
Epoch 21/25
3/3 [==============================] - 0s 62ms/step - loss: 0.4157 - accuracy: 0.8902 - val_loss: 0.4053 - val_accuracy: 0.9048
Epoch 22/25
3/3 [==============================] - 0s 50ms/step - loss: 0.3952 - accuracy: 0.8659 - val_loss: 0.3934 - val_accuracy: 0.9048
Epoch 23/25
3/3 [==============================] - 0s 65ms/step - loss: 0.4390 - accuracy: 0.8537 - val_loss: 0.3783 - val_accuracy: 0.9048
Epoch 24/25
3/3 [==============================] - 0s 61ms/step - loss: 0.3877 - accuracy: 0.8415 - val_loss: 0.3624 - val_accuracy: 0.9048
Epoch 25/25
3/3 [==============================] - 0s 59ms/step - loss: 0.3826 - accuracy: 0.9146 - val_loss: 0.3494 - val_accuracy: 0.9048
1/1 [==============================] - 0s 96ms/step - loss: 0.3815 - accuracy: 0.8846

In [77]:
mode.append('ANN')
tr_precision.append(0)
tr_recall.append(0)
tr_f1.append(0)
tr_accu.append(0)

te_precision.append(0)
te_recall.append(0)
te_f1.append(0)
te_accu.append(accuracy)

In [26]:
dict = {'classifier': mode, 'tr_precision': tr_precision, 'tr_recall': tr_recall, 'tr_f1 ': tr_f1,'tr_accuracy': tr_accu,
         'te_precision': te_precision, 'te_recall': te_recall, 'te_f1 ': te_f1, 'te_accuracy': te_accu}

df = pd.DataFrame(dict)

In [27]:
df

,classifier,tr_precision,tr_recall,tr_f1,tr_accuracy,te_precision,te_recall,te_f1,te_accuracy
0,LogR,1.000,1.000,1.000,1.000,0.714,0.667,0.550,0.556
1,gNB,1.000,1.000,1.000,1.000,0.750,0.750,0.667,0.667
2,SVM,1.000,1.000,1.000,1.000,0.750,0.750,0.667,0.667
3,DT,1.000,1.000,1.000,1.000,0.750,0.750,0.667,0.667
4,RF,1.000,1.000,1.000,1.000,0.750,0.750,0.667,0.667
5,KNN,0.913,0.875,0.881,0.886,0.167,0.500,0.250,0.333
6,LDA,0.975,0.969,0.971,0.971,0.714,0.667,0.550,0.556
7,mNB,1.000,1.000,1.000,1.000,0.714,0.667,0.550,0.556
8,ABC,1.000,1.000,1.000,1.000,0.750,0.750,0.667,0.667
9,GBC,1.000,1.000,1.000,1.000,0.750,0.750,0.667,0.667
10,ETC,1.000,1.000,1.000,1.000,0.714,0.667,0.550,0.556
11,BC,1.000,1.000,1.000,1.000,0.750,0.750,0.667,0.667

In [302]:
df.to_csv(file_out, index=False)